# Generated by Django 3.1.1 on 2020-10-06 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='solution',
            fields=[
                ('solutionId', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('solutionName', models.CharField(max_length=50, verbose_name='方案名称')),
                ('codeAddr', models.CharField(max_length=200, verbose_name='代码地址')),
                ('taskName', models.CharField(max_length=200, verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '方案',
                'verbose_name_plural': '方案',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('task_name', models.CharField(max_length=100, unique=True, verbose_name='任务名称')),
                ('task_type', models.CharField(max_length=100, verbose_name='任务类型')),
                ('matched_dataset', models.CharField(max_length=100, verbose_name='数据集')),
                ('description', models.TextField(verbose_name='描述')),
                ('task_status', models.IntegerField(default=0, verbose_name='任务状态')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
    ]
