# Generated by Django 3.1.1 on 2020-10-10 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_solution_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='solution',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='solution',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
    ]
